# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ProfilerStringTable.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ProfilerStringTable.proto',
  package='NV.Profiler.Messages',
  serialized_pb=_b('\n\x19ProfilerStringTable.proto\x12\x14NV.Profiler.Messages\"&\n\x13ProfilerStringTable\x12\x0f\n\x07Strings\x18\x01 \x03(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PROFILERSTRINGTABLE = _descriptor.Descriptor(
  name='ProfilerStringTable',
  full_name='NV.Profiler.Messages.ProfilerStringTable',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Strings', full_name='NV.Profiler.Messages.ProfilerStringTable.Strings', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=89,
)

DESCRIPTOR.message_types_by_name['ProfilerStringTable'] = _PROFILERSTRINGTABLE

ProfilerStringTable = _reflection.GeneratedProtocolMessageType('ProfilerStringTable', (_message.Message,), dict(
  DESCRIPTOR = _PROFILERSTRINGTABLE,
  __module__ = 'ProfilerStringTable_pb2'
  # @@protoc_insertion_point(class_scope:NV.Profiler.Messages.ProfilerStringTable)
  ))
_sym_db.RegisterMessage(ProfilerStringTable)


# @@protoc_insertion_point(module_scope)
