# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.descriptor import (
    EnumDescriptor as google___protobuf___descriptor___EnumDescriptor,
    FileDescriptor as google___protobuf___descriptor___FileDescriptor,
)

from google.protobuf.internal.enum_type_wrapper import (
    EnumTypeWrapper as google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    NewType as typing___NewType,
    cast as typing___cast,
)


builtin___int = int


DESCRIPTOR: google___protobuf___descriptor___FileDescriptor = ...

ProfilerCategoryValue = typing___NewType('ProfilerCategoryValue', builtin___int)
type___ProfilerCategoryValue = ProfilerCategoryValue
ProfilerCategory: _ProfilerCategory
class _ProfilerCategory(google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper[ProfilerCategoryValue]):
    DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
    CategoryInvalid = typing___cast(ProfilerCategoryValue, 0)
    CategoryConfiguration = typing___cast(ProfilerCategoryValue, 1)
    CategoryControl = typing___cast(ProfilerCategoryValue, 2)
    CategoryResults = typing___cast(ProfilerCategoryValue, 3)
    CategoryStatus = typing___cast(ProfilerCategoryValue, 4)
CategoryInvalid = typing___cast(ProfilerCategoryValue, 0)
CategoryConfiguration = typing___cast(ProfilerCategoryValue, 1)
CategoryControl = typing___cast(ProfilerCategoryValue, 2)
CategoryResults = typing___cast(ProfilerCategoryValue, 3)
CategoryStatus = typing___cast(ProfilerCategoryValue, 4)
type___ProfilerCategory = ProfilerCategory
