# This file is part of the Extra-P software (http://www.scalasca.org/software/extra-p)
#
# Copyright (c) 2024, Technical University of Darmstadt, Germany
#
# This software may be modified and distributed under the terms of a BSD-style license.
# See the LICENSE file in the base directory for details.

import argparse
import sys

from pycubexr import CubexParser


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('path', action='store', type=str)
    parser.add_argument('--metric', type=str, default='time')
    parser.add_argument('--threshold', type=float, default=0.01)
    parser.add_argument('--reverse', action='store_true', default=False)

    args = parser.parse_args()

    with CubexParser(args.path) as cubexFile:
        metric = cubexFile.get_metric_by_name(args.metric)
        metric_values = cubexFile.get_metric_values(metric, False)

        total = sum(metric_values.value(cn, False, True) for cn in cubexFile.get_root_cnodes())

        if total == 0:
            return

        included_names = set()
        excluded_names = set()

        for cnode in cubexFile.all_cnodes():
            if metric_values.value(cnode, True) / total >= args.threshold:
                included_names.add(cnode.region.mangled_name)
            else:
                excluded_names.add(cnode.region.mangled_name)
        if args.reverse:
            included_names, excluded_names = excluded_names, included_names

    filter_file = f"#Generated by Extra-P {' '.join(sys.argv[1:])}\n"
    filter_file += "SCOREP_REGION_NAMES_BEGIN\n"
    if len(excluded_names) <= len(included_names):
        filter_file += '  EXCLUDE MANGLED ' + '\n    '.join(name.replace(' ', '\\ ') for name in excluded_names)
    else:
        filter_file += '  EXCLUDE *\n'
        filter_file += '  INCLUDE MANGLED ' + '\n    '.join(name.replace(' ', '\\ ') for name in included_names)
    filter_file += '\nSCOREP_REGION_NAMES_END\n'
    print(filter_file)


if __name__ == '__main__':
    main()
