# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ProfilerReportCommon.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ProfilerReportCommon.proto',
  package='NV.Profiler.Messages',
  serialized_pb=_b('\n\x1aProfilerReportCommon.proto\x12\x14NV.Profiler.Messages\"+\n\x08Uint64x3\x12\t\n\x01X\x18\x01 \x01(\x04\x12\t\n\x01Y\x18\x02 \x01(\x04\x12\t\n\x01Z\x18\x03 \x01(\x04\"\xb6\x01\n\nSourceData\x12\x11\n\tReference\x18\x01 \x01(\x04\x12\x0c\n\x04\x43ode\x18\x02 \x01(\t\x12\x14\n\x0cIntermediate\x18\x03 \x01(\x0c\x12\x0e\n\x06\x42inary\x18\x04 \x01(\x0c\x12\x38\n\tSassLevel\x18\x05 \x01(\x0e\x32%.NV.Profiler.Messages.SourceSassLevel\x12\x12\n\nSMRevision\x18\x06 \x01(\r\x12\x13\n\x0b\x42inaryFlags\x18\x07 \x01(\r\"r\n\x12\x45xecutableSettings\x12\x16\n\x0e\x45xecutablePath\x18\x01 \x02(\t\x12\x15\n\rWorkDirectory\x18\x02 \x01(\t\x12\x18\n\x10\x43mdlineAgruments\x18\x03 \x01(\t\x12\x13\n\x0b\x45nvironment\x18\x04 \x01(\t*Y\n\x07\x41PIType\x12\x10\n\x0c\x41PIType_CUDA\x10\x00\x12\x12\n\x0e\x41PIType_OpenCL\x10\x01\x12\x14\n\x10\x41PIType_Direct3D\x10\x02\x12\x12\n\x0e\x41PIType_OpenGL\x10\x03*\xe9\x01\n\x0fSourceSassLevel\x12\x19\n\x15SourceSassLevel_Unset\x10\x00\x12\x19\n\x15SourceSassLevel_Sass1\x10\x01\x12\x19\n\x15SourceSassLevel_Sass2\x10\x02\x12\x19\n\x15SourceSassLevel_Sass3\x10\x03\x12\x19\n\x15SourceSassLevel_Sass4\x10\x04\x12\x19\n\x15SourceSassLevel_Sass5\x10\x05\x12\x19\n\x15SourceSassLevel_Sass6\x10\x06\x12\x19\n\x15SourceSassLevel_Sass7\x10\x07')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_APITYPE = _descriptor.EnumDescriptor(
  name='APIType',
  full_name='NV.Profiler.Messages.APIType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='APIType_CUDA', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='APIType_OpenCL', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='APIType_Direct3D', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='APIType_OpenGL', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=398,
  serialized_end=487,
)
_sym_db.RegisterEnumDescriptor(_APITYPE)

APIType = enum_type_wrapper.EnumTypeWrapper(_APITYPE)
_SOURCESASSLEVEL = _descriptor.EnumDescriptor(
  name='SourceSassLevel',
  full_name='NV.Profiler.Messages.SourceSassLevel',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SourceSassLevel_Unset', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SourceSassLevel_Sass1', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SourceSassLevel_Sass2', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SourceSassLevel_Sass3', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SourceSassLevel_Sass4', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SourceSassLevel_Sass5', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SourceSassLevel_Sass6', index=6, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SourceSassLevel_Sass7', index=7, number=7,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=490,
  serialized_end=723,
)
_sym_db.RegisterEnumDescriptor(_SOURCESASSLEVEL)

SourceSassLevel = enum_type_wrapper.EnumTypeWrapper(_SOURCESASSLEVEL)
APIType_CUDA = 0
APIType_OpenCL = 1
APIType_Direct3D = 2
APIType_OpenGL = 3
SourceSassLevel_Unset = 0
SourceSassLevel_Sass1 = 1
SourceSassLevel_Sass2 = 2
SourceSassLevel_Sass3 = 3
SourceSassLevel_Sass4 = 4
SourceSassLevel_Sass5 = 5
SourceSassLevel_Sass6 = 6
SourceSassLevel_Sass7 = 7



_UINT64X3 = _descriptor.Descriptor(
  name='Uint64x3',
  full_name='NV.Profiler.Messages.Uint64x3',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='X', full_name='NV.Profiler.Messages.Uint64x3.X', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Y', full_name='NV.Profiler.Messages.Uint64x3.Y', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Z', full_name='NV.Profiler.Messages.Uint64x3.Z', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=95,
)


_SOURCEDATA = _descriptor.Descriptor(
  name='SourceData',
  full_name='NV.Profiler.Messages.SourceData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Reference', full_name='NV.Profiler.Messages.SourceData.Reference', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Code', full_name='NV.Profiler.Messages.SourceData.Code', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Intermediate', full_name='NV.Profiler.Messages.SourceData.Intermediate', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Binary', full_name='NV.Profiler.Messages.SourceData.Binary', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='SassLevel', full_name='NV.Profiler.Messages.SourceData.SassLevel', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='SMRevision', full_name='NV.Profiler.Messages.SourceData.SMRevision', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='BinaryFlags', full_name='NV.Profiler.Messages.SourceData.BinaryFlags', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=98,
  serialized_end=280,
)


_EXECUTABLESETTINGS = _descriptor.Descriptor(
  name='ExecutableSettings',
  full_name='NV.Profiler.Messages.ExecutableSettings',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ExecutablePath', full_name='NV.Profiler.Messages.ExecutableSettings.ExecutablePath', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='WorkDirectory', full_name='NV.Profiler.Messages.ExecutableSettings.WorkDirectory', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='CmdlineAgruments', full_name='NV.Profiler.Messages.ExecutableSettings.CmdlineAgruments', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Environment', full_name='NV.Profiler.Messages.ExecutableSettings.Environment', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=282,
  serialized_end=396,
)

_SOURCEDATA.fields_by_name['SassLevel'].enum_type = _SOURCESASSLEVEL
DESCRIPTOR.message_types_by_name['Uint64x3'] = _UINT64X3
DESCRIPTOR.message_types_by_name['SourceData'] = _SOURCEDATA
DESCRIPTOR.message_types_by_name['ExecutableSettings'] = _EXECUTABLESETTINGS
DESCRIPTOR.enum_types_by_name['APIType'] = _APITYPE
DESCRIPTOR.enum_types_by_name['SourceSassLevel'] = _SOURCESASSLEVEL

Uint64x3 = _reflection.GeneratedProtocolMessageType('Uint64x3', (_message.Message,), dict(
  DESCRIPTOR = _UINT64X3,
  __module__ = 'ProfilerReportCommon_pb2'
  # @@protoc_insertion_point(class_scope:NV.Profiler.Messages.Uint64x3)
  ))
_sym_db.RegisterMessage(Uint64x3)

SourceData = _reflection.GeneratedProtocolMessageType('SourceData', (_message.Message,), dict(
  DESCRIPTOR = _SOURCEDATA,
  __module__ = 'ProfilerReportCommon_pb2'
  # @@protoc_insertion_point(class_scope:NV.Profiler.Messages.SourceData)
  ))
_sym_db.RegisterMessage(SourceData)

ExecutableSettings = _reflection.GeneratedProtocolMessageType('ExecutableSettings', (_message.Message,), dict(
  DESCRIPTOR = _EXECUTABLESETTINGS,
  __module__ = 'ProfilerReportCommon_pb2'
  # @@protoc_insertion_point(class_scope:NV.Profiler.Messages.ExecutableSettings)
  ))
_sym_db.RegisterMessage(ExecutableSettings)


# @@protoc_insertion_point(module_scope)
