// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProfilerMetricOptions.proto

#include "ProfilerMetricOptions.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
class MetricOptionFilterDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<MetricOptionFilter> _instance;
} _MetricOptionFilter_default_instance_;
static void InitDefaultsscc_info_MetricOptionFilter_ProfilerMetricOptions_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_MetricOptionFilter_default_instance_;
    new (ptr) ::MetricOptionFilter();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_MetricOptionFilter_ProfilerMetricOptions_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_MetricOptionFilter_ProfilerMetricOptions_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_ProfilerMetricOptions_2eproto[1];
static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* file_level_enum_descriptors_ProfilerMetricOptions_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_ProfilerMetricOptions_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_ProfilerMetricOptions_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::MetricOptionFilter, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::MetricOptionFilter, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::MetricOptionFilter, minarch_),
  PROTOBUF_FIELD_OFFSET(::MetricOptionFilter, maxarch_),
  0,
  1,
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 7, sizeof(::MetricOptionFilter)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::_MetricOptionFilter_default_instance_),
};

const char descriptor_table_protodef_ProfilerMetricOptions_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\033ProfilerMetricOptions.proto\"J\n\022MetricO"
  "ptionFilter\022\031\n\007MinArch\030\001 \001(\0162\010.GpuArch\022\031"
  "\n\007MaxArch\030\002 \001(\0162\010.GpuArch*\235\001\n\007GpuArch\022\017\n"
  "\013InvalidArch\020\000\022\t\n\005GK10x\020(\022\t\n\005GK11x\020+\022\016\n\n"
  "GK20xGM10x\0202\022\016\n\nGM20xGM10x\0204\022\t\n\005GM20b\0205\022"
  "\t\n\005GP100\020<\022\t\n\005GP10x\020=\022\t\n\005GP10b\020>\022\t\n\005GV10"
  "0\020F\022\t\n\005GV11b\020H\022\t\n\005TU10x\020K"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_ProfilerMetricOptions_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_ProfilerMetricOptions_2eproto_sccs[1] = {
  &scc_info_MetricOptionFilter_ProfilerMetricOptions_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_ProfilerMetricOptions_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_ProfilerMetricOptions_2eproto = {
  false, false, descriptor_table_protodef_ProfilerMetricOptions_2eproto, "ProfilerMetricOptions.proto", 265,
  &descriptor_table_ProfilerMetricOptions_2eproto_once, descriptor_table_ProfilerMetricOptions_2eproto_sccs, descriptor_table_ProfilerMetricOptions_2eproto_deps, 1, 0,
  schemas, file_default_instances, TableStruct_ProfilerMetricOptions_2eproto::offsets,
  file_level_metadata_ProfilerMetricOptions_2eproto, 1, file_level_enum_descriptors_ProfilerMetricOptions_2eproto, file_level_service_descriptors_ProfilerMetricOptions_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_ProfilerMetricOptions_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_ProfilerMetricOptions_2eproto)), true);
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* GpuArch_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_ProfilerMetricOptions_2eproto);
  return file_level_enum_descriptors_ProfilerMetricOptions_2eproto[0];
}
bool GpuArch_IsValid(int value) {
  switch (value) {
    case 0:
    case 40:
    case 43:
    case 50:
    case 52:
    case 53:
    case 60:
    case 61:
    case 62:
    case 70:
    case 72:
    case 75:
      return true;
    default:
      return false;
  }
}


// ===================================================================

class MetricOptionFilter::_Internal {
 public:
  using HasBits = decltype(std::declval<MetricOptionFilter>()._has_bits_);
  static void set_has_minarch(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_maxarch(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
};

MetricOptionFilter::MetricOptionFilter(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:MetricOptionFilter)
}
MetricOptionFilter::MetricOptionFilter(const MetricOptionFilter& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&minarch_, &from.minarch_,
    static_cast<size_t>(reinterpret_cast<char*>(&maxarch_) -
    reinterpret_cast<char*>(&minarch_)) + sizeof(maxarch_));
  // @@protoc_insertion_point(copy_constructor:MetricOptionFilter)
}

void MetricOptionFilter::SharedCtor() {
  ::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
      reinterpret_cast<char*>(&minarch_) - reinterpret_cast<char*>(this)),
      0, static_cast<size_t>(reinterpret_cast<char*>(&maxarch_) -
      reinterpret_cast<char*>(&minarch_)) + sizeof(maxarch_));
}

MetricOptionFilter::~MetricOptionFilter() {
  // @@protoc_insertion_point(destructor:MetricOptionFilter)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void MetricOptionFilter::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void MetricOptionFilter::ArenaDtor(void* object) {
  MetricOptionFilter* _this = reinterpret_cast< MetricOptionFilter* >(object);
  (void)_this;
}
void MetricOptionFilter::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void MetricOptionFilter::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const MetricOptionFilter& MetricOptionFilter::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_MetricOptionFilter_ProfilerMetricOptions_2eproto.base);
  return *internal_default_instance();
}


void MetricOptionFilter::Clear() {
// @@protoc_insertion_point(message_clear_start:MetricOptionFilter)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    ::memset(&minarch_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&maxarch_) -
        reinterpret_cast<char*>(&minarch_)) + sizeof(maxarch_));
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* MetricOptionFilter::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // optional .GpuArch MinArch = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          if (PROTOBUF_PREDICT_TRUE(::GpuArch_IsValid(val))) {
            _internal_set_minarch(static_cast<::GpuArch>(val));
          } else {
            ::PROTOBUF_NAMESPACE_ID::internal::WriteVarint(1, val, mutable_unknown_fields());
          }
        } else goto handle_unusual;
        continue;
      // optional .GpuArch MaxArch = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          if (PROTOBUF_PREDICT_TRUE(::GpuArch_IsValid(val))) {
            _internal_set_maxarch(static_cast<::GpuArch>(val));
          } else {
            ::PROTOBUF_NAMESPACE_ID::internal::WriteVarint(2, val, mutable_unknown_fields());
          }
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* MetricOptionFilter::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:MetricOptionFilter)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional .GpuArch MinArch = 1;
  if (cached_has_bits & 0x00000001u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      1, this->_internal_minarch(), target);
  }

  // optional .GpuArch MaxArch = 2;
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      2, this->_internal_maxarch(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MetricOptionFilter)
  return target;
}

size_t MetricOptionFilter::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:MetricOptionFilter)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    // optional .GpuArch MinArch = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_minarch());
    }

    // optional .GpuArch MaxArch = 2;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_maxarch());
    }

  }
  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void MetricOptionFilter::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:MetricOptionFilter)
  GOOGLE_DCHECK_NE(&from, this);
  const MetricOptionFilter* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<MetricOptionFilter>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:MetricOptionFilter)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:MetricOptionFilter)
    MergeFrom(*source);
  }
}

void MetricOptionFilter::MergeFrom(const MetricOptionFilter& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:MetricOptionFilter)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      minarch_ = from.minarch_;
    }
    if (cached_has_bits & 0x00000002u) {
      maxarch_ = from.maxarch_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void MetricOptionFilter::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:MetricOptionFilter)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MetricOptionFilter::CopyFrom(const MetricOptionFilter& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MetricOptionFilter)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MetricOptionFilter::IsInitialized() const {
  return true;
}

void MetricOptionFilter::InternalSwap(MetricOptionFilter* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(MetricOptionFilter, maxarch_)
      + sizeof(MetricOptionFilter::maxarch_)
      - PROTOBUF_FIELD_OFFSET(MetricOptionFilter, minarch_)>(
          reinterpret_cast<char*>(&minarch_),
          reinterpret_cast<char*>(&other->minarch_));
}

::PROTOBUF_NAMESPACE_ID::Metadata MetricOptionFilter::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::MetricOptionFilter* Arena::CreateMaybeMessage< ::MetricOptionFilter >(Arena* arena) {
  return Arena::CreateMessageInternal< ::MetricOptionFilter >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
