# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.descriptor import (
    EnumDescriptor as google___protobuf___descriptor___EnumDescriptor,
    FileDescriptor as google___protobuf___descriptor___FileDescriptor,
)

from google.protobuf.internal.enum_type_wrapper import (
    EnumTypeWrapper as google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    NewType as typing___NewType,
    cast as typing___cast,
)


builtin___int = int


DESCRIPTOR: google___protobuf___descriptor___FileDescriptor = ...

NvtxCategoryValue = typing___NewType('NvtxCategoryValue', builtin___int)
type___NvtxCategoryValue = NvtxCategoryValue
NvtxCategory: _NvtxCategory
class _NvtxCategory(google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper[NvtxCategoryValue]):
    DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
    NvtxCategoryInvalid = typing___cast(NvtxCategoryValue, 0)
    NvtxCategoryState = typing___cast(NvtxCategoryValue, 1)
NvtxCategoryInvalid = typing___cast(NvtxCategoryValue, 0)
NvtxCategoryState = typing___cast(NvtxCategoryValue, 1)
type___NvtxCategory = NvtxCategory
