# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from .ProfilerCategories_pb2 import (
    ProfilerCategoryValue as ProfilerCategories_pb2___ProfilerCategoryValue,
)

from .ProfilerCommon_pb2 import (
    LaunchData as ProfilerCommon_pb2___LaunchData,
    SourceData as ProfilerCommon_pb2___SourceData,
)

from .ProfilerStringTable_pb2 import (
    ProfilerStringTable as ProfilerStringTable_pb2___ProfilerStringTable,
)

from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    EnumDescriptor as google___protobuf___descriptor___EnumDescriptor,
    FileDescriptor as google___protobuf___descriptor___FileDescriptor,
)

from google.protobuf.internal.containers import (
    RepeatedCompositeFieldContainer as google___protobuf___internal___containers___RepeatedCompositeFieldContainer,
)

from google.protobuf.internal.enum_type_wrapper import (
    EnumTypeWrapper as google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    Iterable as typing___Iterable,
    NewType as typing___NewType,
    Optional as typing___Optional,
    Text as typing___Text,
    cast as typing___cast,
)

from typing import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int


DESCRIPTOR: google___protobuf___descriptor___FileDescriptor = ...

ProfilerResultsMethodValue = typing___NewType('ProfilerResultsMethodValue', builtin___int)
type___ProfilerResultsMethodValue = ProfilerResultsMethodValue
ProfilerResultsMethod: _ProfilerResultsMethod
class _ProfilerResultsMethod(google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper[ProfilerResultsMethodValue]):
    DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
    InvalidResultsMethod = typing___cast(ProfilerResultsMethodValue, 0)
    MethodSourceMessage = typing___cast(ProfilerResultsMethodValue, 1)
    MethodResultMessage = typing___cast(ProfilerResultsMethodValue, 2)
    MethodClearCachedProfilerSourceMessage = typing___cast(ProfilerResultsMethodValue, 3)
InvalidResultsMethod = typing___cast(ProfilerResultsMethodValue, 0)
MethodSourceMessage = typing___cast(ProfilerResultsMethodValue, 1)
MethodResultMessage = typing___cast(ProfilerResultsMethodValue, 2)
MethodClearCachedProfilerSourceMessage = typing___cast(ProfilerResultsMethodValue, 3)
type___ProfilerResultsMethod = ProfilerResultsMethod

class MetricValueMessage(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    StringValue: typing___Text = ...
    FloatValue: builtin___float = ...
    DoubleValue: builtin___float = ...
    Uint32Value: builtin___int = ...
    Uint64Value: builtin___int = ...

    def __init__(self,
        *,
        StringValue : typing___Optional[typing___Text] = None,
        FloatValue : typing___Optional[builtin___float] = None,
        DoubleValue : typing___Optional[builtin___float] = None,
        Uint32Value : typing___Optional[builtin___int] = None,
        Uint64Value : typing___Optional[builtin___int] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"DoubleValue",b"DoubleValue",u"FloatValue",b"FloatValue",u"StringValue",b"StringValue",u"Uint32Value",b"Uint32Value",u"Uint64Value",b"Uint64Value"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"DoubleValue",b"DoubleValue",u"FloatValue",b"FloatValue",u"StringValue",b"StringValue",u"Uint32Value",b"Uint32Value",u"Uint64Value",b"Uint64Value"]) -> None: ...
type___MetricValueMessage = MetricValueMessage

class MetricListElementMessage(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

    @property
    def CorrelationId(self) -> type___MetricValueMessage: ...

    @property
    def ElementValue(self) -> type___MetricValueMessage: ...

    def __init__(self,
        *,
        CorrelationId : typing___Optional[type___MetricValueMessage] = None,
        ElementValue : typing___Optional[type___MetricValueMessage] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"CorrelationId",b"CorrelationId",u"ElementValue",b"ElementValue"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"CorrelationId",b"CorrelationId",u"ElementValue",b"ElementValue"]) -> None: ...
type___MetricListElementMessage = MetricListElementMessage

class MetricResultMessage(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    MetricNameId: builtin___int = ...

    @property
    def MetricValue(self) -> type___MetricValueMessage: ...

    @property
    def MetricValueList(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[type___MetricListElementMessage]: ...

    def __init__(self,
        *,
        MetricNameId : typing___Optional[builtin___int] = None,
        MetricValue : typing___Optional[type___MetricValueMessage] = None,
        MetricValueList : typing___Optional[typing___Iterable[type___MetricListElementMessage]] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"MetricNameId",b"MetricNameId",u"MetricValue",b"MetricValue"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"MetricNameId",b"MetricNameId",u"MetricValue",b"MetricValue",u"MetricValueList",b"MetricValueList"]) -> None: ...
type___MetricResultMessage = MetricResultMessage

class ProfilerSourceMessage(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    class TypeInfo(google___protobuf___message___Message):
        DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
        Category: ProfilerCategories_pb2___ProfilerCategoryValue = ...
        Method: type___ProfilerResultsMethodValue = ...

        def __init__(self,
            *,
            Category : typing___Optional[ProfilerCategories_pb2___ProfilerCategoryValue] = None,
            Method : typing___Optional[type___ProfilerResultsMethodValue] = None,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions___Literal[u"Category",b"Category",u"Method",b"Method"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"Category",b"Category",u"Method",b"Method"]) -> None: ...
    type___TypeInfo = TypeInfo


    @property
    def Source(self) -> ProfilerCommon_pb2___SourceData: ...

    def __init__(self,
        *,
        Source : typing___Optional[ProfilerCommon_pb2___SourceData] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"Source",b"Source"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"Source",b"Source"]) -> None: ...
type___ProfilerSourceMessage = ProfilerSourceMessage

class ClearCachedProfilerSourceMessage(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    class TypeInfo(google___protobuf___message___Message):
        DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
        Category: ProfilerCategories_pb2___ProfilerCategoryValue = ...
        Method: type___ProfilerResultsMethodValue = ...

        def __init__(self,
            *,
            Category : typing___Optional[ProfilerCategories_pb2___ProfilerCategoryValue] = None,
            Method : typing___Optional[type___ProfilerResultsMethodValue] = None,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions___Literal[u"Category",b"Category",u"Method",b"Method"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"Category",b"Category",u"Method",b"Method"]) -> None: ...
    type___TypeInfo = TypeInfo


    def __init__(self,
        ) -> None: ...
type___ClearCachedProfilerSourceMessage = ClearCachedProfilerSourceMessage

class ProfilerVersionInfoMessage(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    Provider: typing___Text = ...
    Version: typing___Text = ...

    def __init__(self,
        *,
        Provider : typing___Optional[typing___Text] = None,
        Version : typing___Optional[typing___Text] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"Provider",b"Provider",u"Version",b"Version"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"Provider",b"Provider",u"Version",b"Version"]) -> None: ...
type___ProfilerVersionInfoMessage = ProfilerVersionInfoMessage

class ProfileSeriesInfoMessage(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    SeriesID: builtin___int = ...
    CombinationStr: typing___Text = ...

    def __init__(self,
        *,
        SeriesID : typing___Optional[builtin___int] = None,
        CombinationStr : typing___Optional[typing___Text] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"CombinationStr",b"CombinationStr",u"SeriesID",b"SeriesID"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"CombinationStr",b"CombinationStr",u"SeriesID",b"SeriesID"]) -> None: ...
type___ProfileSeriesInfoMessage = ProfileSeriesInfoMessage

class ProfilerResultMessage(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    class TypeInfo(google___protobuf___message___Message):
        DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
        Category: ProfilerCategories_pb2___ProfilerCategoryValue = ...
        Method: type___ProfilerResultsMethodValue = ...

        def __init__(self,
            *,
            Category : typing___Optional[ProfilerCategories_pb2___ProfilerCategoryValue] = None,
            Method : typing___Optional[type___ProfilerResultsMethodValue] = None,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions___Literal[u"Category",b"Category",u"Method",b"Method"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"Category",b"Category",u"Method",b"Method"]) -> None: ...
    type___TypeInfo = TypeInfo

    ID: builtin___int = ...
    UnsupportedDevice: builtin___bool = ...

    @property
    def Launch(self) -> ProfilerCommon_pb2___LaunchData: ...

    @property
    def MetricResults(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[type___MetricResultMessage]: ...

    @property
    def Source(self) -> ProfilerCommon_pb2___SourceData: ...

    @property
    def StringTable(self) -> ProfilerStringTable_pb2___ProfilerStringTable: ...

    @property
    def VersionInfo(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[type___ProfilerVersionInfoMessage]: ...

    @property
    def SeriesInfo(self) -> type___ProfileSeriesInfoMessage: ...

    def __init__(self,
        *,
        ID : typing___Optional[builtin___int] = None,
        Launch : typing___Optional[ProfilerCommon_pb2___LaunchData] = None,
        MetricResults : typing___Optional[typing___Iterable[type___MetricResultMessage]] = None,
        Source : typing___Optional[ProfilerCommon_pb2___SourceData] = None,
        StringTable : typing___Optional[ProfilerStringTable_pb2___ProfilerStringTable] = None,
        UnsupportedDevice : typing___Optional[builtin___bool] = None,
        VersionInfo : typing___Optional[typing___Iterable[type___ProfilerVersionInfoMessage]] = None,
        SeriesInfo : typing___Optional[type___ProfileSeriesInfoMessage] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"ID",b"ID",u"Launch",b"Launch",u"SeriesInfo",b"SeriesInfo",u"Source",b"Source",u"StringTable",b"StringTable",u"UnsupportedDevice",b"UnsupportedDevice"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"ID",b"ID",u"Launch",b"Launch",u"MetricResults",b"MetricResults",u"SeriesInfo",b"SeriesInfo",u"Source",b"Source",u"StringTable",b"StringTable",u"UnsupportedDevice",b"UnsupportedDevice",u"VersionInfo",b"VersionInfo"]) -> None: ...
type___ProfilerResultMessage = ProfilerResultMessage
