# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ProfilerCommon.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'ProfilerCommon.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14ProfilerCommon.proto\"+\n\x08Uint64x3\x12\t\n\x01X\x18\x01 \x01(\x04\x12\t\n\x01Y\x18\x02 \x01(\x04\x12\t\n\x01Z\x18\x03 \x01(\x04\"\xa8\x03\n\nLaunchData\x12\x11\n\tProcessID\x18\x02 \x02(\r\x12\x10\n\x08ThreadID\x18\x03 \x02(\r\x12\x11\n\tAPICallID\x18\x04 \x02(\x04\x12\x15\n\x03\x41PI\x18\x05 \x02(\x0e\x32\x08.APIType\x12\x10\n\x08KernelID\x18\x06 \x02(\x04\x12\x19\n\x11KernelMangledName\x18\x07 \x02(\t\x12\x1a\n\x12KernelFunctionName\x18\x08 \x02(\t\x12\x1b\n\x13KernelDemangledName\x18\t \x02(\t\x12\x15\n\rProgramHandle\x18\n \x02(\x04\x12\x15\n\rContextHandle\x18\x0b \x02(\x04\x12\x10\n\x08\x44\x65viceID\x18\x0c \x02(\x04\x12\x16\n\x0eWorkDimensions\x18\r \x02(\r\x12#\n\x10GlobalWorkOffset\x18\x0e \x02(\x0b\x32\t.Uint64x3\x12!\n\x0eGlobalWorkSize\x18\x0f \x02(\x0b\x32\t.Uint64x3\x12 \n\rLocalWorkSize\x18\x10 \x02(\x0b\x32\t.Uint64x3\x12\x11\n\tContextID\x18\x11 \x01(\r\x12\x10\n\x08StreamID\x18\x12 \x01(\r\"\xa1\x01\n\nSourceData\x12\x11\n\tReference\x18\x01 \x01(\x04\x12\x0c\n\x04\x43ode\x18\x02 \x01(\t\x12\x14\n\x0cIntermediate\x18\x03 \x01(\x0c\x12\x0e\n\x06\x42inary\x18\x04 \x01(\x0c\x12#\n\tSassLevel\x18\x05 \x01(\x0e\x32\x10.SourceSassLevel\x12\x12\n\nSMRevision\x18\x06 \x01(\r\x12\x13\n\x0b\x42inaryFlags\x18\x07 \x01(\r*Y\n\x07\x41PIType\x12\x10\n\x0c\x41PIType_CUDA\x10\x00\x12\x12\n\x0e\x41PIType_OpenCL\x10\x01\x12\x14\n\x10\x41PIType_Direct3D\x10\x02\x12\x12\n\x0e\x41PIType_OpenGL\x10\x03*\xe9\x01\n\x0fSourceSassLevel\x12\x19\n\x15SourceSassLevel_Unset\x10\x00\x12\x19\n\x15SourceSassLevel_Sass1\x10\x01\x12\x19\n\x15SourceSassLevel_Sass2\x10\x02\x12\x19\n\x15SourceSassLevel_Sass3\x10\x03\x12\x19\n\x15SourceSassLevel_Sass4\x10\x04\x12\x19\n\x15SourceSassLevel_Sass5\x10\x05\x12\x19\n\x15SourceSassLevel_Sass6\x10\x06\x12\x19\n\x15SourceSassLevel_Sass7\x10\x07')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ProfilerCommon_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_APITYPE']._serialized_start=660
  _globals['_APITYPE']._serialized_end=749
  _globals['_SOURCESASSLEVEL']._serialized_start=752
  _globals['_SOURCESASSLEVEL']._serialized_end=985
  _globals['_UINT64X3']._serialized_start=24
  _globals['_UINT64X3']._serialized_end=67
  _globals['_LAUNCHDATA']._serialized_start=70
  _globals['_LAUNCHDATA']._serialized_end=494
  _globals['_SOURCEDATA']._serialized_start=497
  _globals['_SOURCEDATA']._serialized_end=658
# @@protoc_insertion_point(module_scope)
