# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: RuleResults.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'RuleResults.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import ProfilerSection_pb2 as ProfilerSection__pb2
from . import ProfilerCommon_pb2 as ProfilerCommon__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11RuleResults.proto\x1a\x15ProfilerSection.proto\x1a\x14ProfilerCommon.proto\"J\n\x11RuleResultMessage\x12\x0f\n\x07Message\x18\x01 \x02(\t\x12$\n\x04Type\x18\x02 \x02(\x0e\x32\x16.RuleResultMessageType\"(\n\x12RuleResultProposal\x12\x12\n\nIdentifier\x18\x01 \x02(\t\"\x98\x02\n\x12RuleResultBodyItem\x12#\n\x07Message\x18\x01 \x01(\x0b\x32\x12.RuleResultMessage\x12$\n\x05Table\x18\x02 \x01(\x0b\x32\x15.ProfilerSectionTable\x12*\n\x08\x42\x61rChart\x18\x03 \x01(\x0b\x32\x18.ProfilerSectionBarChart\x12\x36\n\x0eHistogramChart\x18\x04 \x01(\x0b\x32\x1e.ProfilerSectionHistogramChart\x12,\n\tLineChart\x18\x05 \x01(\x0b\x32\x19.ProfilerSectionLineChart\x12%\n\x08Proposal\x18\x06 \x01(\x0b\x32\x13.RuleResultProposal\"4\n\x0eRuleResultBody\x12\"\n\x05Items\x18\x01 \x03(\x0b\x32\x13.RuleResultBodyItem\"o\n\nRuleResult\x12\x12\n\nIdentifier\x18\x01 \x02(\t\x12\x13\n\x0b\x44isplayName\x18\x02 \x02(\t\x12\x1d\n\x04\x42ody\x18\x03 \x01(\x0b\x32\x0f.RuleResultBody\x12\x19\n\x11SectionIdentifier\x18\x04 \x01(\t\"/\n\x0bRuleResults\x12 \n\x0bRuleResults\x18\x01 \x03(\x0b\x32\x0b.RuleResult*B\n\x15RuleResultMessageType\x12\t\n\x05None_\x10\x00\x12\x06\n\x02Ok\x10\x01\x12\x0b\n\x07Warning\x10\x02\x12\t\n\x05\x45rror\x10\x03')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RuleResults_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RULERESULTMESSAGETYPE']._serialized_start=683
  _globals['_RULERESULTMESSAGETYPE']._serialized_end=749
  _globals['_RULERESULTMESSAGE']._serialized_start=66
  _globals['_RULERESULTMESSAGE']._serialized_end=140
  _globals['_RULERESULTPROPOSAL']._serialized_start=142
  _globals['_RULERESULTPROPOSAL']._serialized_end=182
  _globals['_RULERESULTBODYITEM']._serialized_start=185
  _globals['_RULERESULTBODYITEM']._serialized_end=465
  _globals['_RULERESULTBODY']._serialized_start=467
  _globals['_RULERESULTBODY']._serialized_end=519
  _globals['_RULERESULT']._serialized_start=521
  _globals['_RULERESULT']._serialized_end=632
  _globals['_RULERESULTS']._serialized_start=634
  _globals['_RULERESULTS']._serialized_end=681
# @@protoc_insertion_point(module_scope)
