# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from .ProfilerSection_pb2 import (
    ProfilerSectionBarChart as ProfilerSection_pb2___ProfilerSectionBarChart,
    ProfilerSectionHistogramChart as ProfilerSection_pb2___ProfilerSectionHistogramChart,
    ProfilerSectionLineChart as ProfilerSection_pb2___ProfilerSectionLineChart,
    ProfilerSectionTable as ProfilerSection_pb2___ProfilerSectionTable,
)

from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    EnumDescriptor as google___protobuf___descriptor___EnumDescriptor,
    FileDescriptor as google___protobuf___descriptor___FileDescriptor,
)

from google.protobuf.internal.containers import (
    RepeatedCompositeFieldContainer as google___protobuf___internal___containers___RepeatedCompositeFieldContainer,
)

from google.protobuf.internal.enum_type_wrapper import (
    EnumTypeWrapper as google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    Iterable as typing___Iterable,
    NewType as typing___NewType,
    Optional as typing___Optional,
    Text as typing___Text,
    cast as typing___cast,
)

from typing import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int


DESCRIPTOR: google___protobuf___descriptor___FileDescriptor = ...

RuleResultMessageTypeValue = typing___NewType('RuleResultMessageTypeValue', builtin___int)
type___RuleResultMessageTypeValue = RuleResultMessageTypeValue
RuleResultMessageType: _RuleResultMessageType
class _RuleResultMessageType(google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper[RuleResultMessageTypeValue]):
    DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
    Ok = typing___cast(RuleResultMessageTypeValue, 1)
    Warning = typing___cast(RuleResultMessageTypeValue, 2)
    Error = typing___cast(RuleResultMessageTypeValue, 3)
Ok = typing___cast(RuleResultMessageTypeValue, 1)
Warning = typing___cast(RuleResultMessageTypeValue, 2)
Error = typing___cast(RuleResultMessageTypeValue, 3)
type___RuleResultMessageType = RuleResultMessageType

class RuleResultMessage(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    Message: typing___Text = ...
    Type: type___RuleResultMessageTypeValue = ...

    def __init__(self,
        *,
        Message : typing___Optional[typing___Text] = None,
        Type : typing___Optional[type___RuleResultMessageTypeValue] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"Message",b"Message",u"Type",b"Type"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"Message",b"Message",u"Type",b"Type"]) -> None: ...
type___RuleResultMessage = RuleResultMessage

class RuleResultProposal(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    Identifier: typing___Text = ...

    def __init__(self,
        *,
        Identifier : typing___Optional[typing___Text] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"Identifier",b"Identifier"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"Identifier",b"Identifier"]) -> None: ...
type___RuleResultProposal = RuleResultProposal

class RuleResultBodyItem(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

    @property
    def Message(self) -> type___RuleResultMessage: ...

    @property
    def Table(self) -> ProfilerSection_pb2___ProfilerSectionTable: ...

    @property
    def BarChart(self) -> ProfilerSection_pb2___ProfilerSectionBarChart: ...

    @property
    def HistogramChart(self) -> ProfilerSection_pb2___ProfilerSectionHistogramChart: ...

    @property
    def LineChart(self) -> ProfilerSection_pb2___ProfilerSectionLineChart: ...

    @property
    def Proposal(self) -> type___RuleResultProposal: ...

    def __init__(self,
        *,
        Message : typing___Optional[type___RuleResultMessage] = None,
        Table : typing___Optional[ProfilerSection_pb2___ProfilerSectionTable] = None,
        BarChart : typing___Optional[ProfilerSection_pb2___ProfilerSectionBarChart] = None,
        HistogramChart : typing___Optional[ProfilerSection_pb2___ProfilerSectionHistogramChart] = None,
        LineChart : typing___Optional[ProfilerSection_pb2___ProfilerSectionLineChart] = None,
        Proposal : typing___Optional[type___RuleResultProposal] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"BarChart",b"BarChart",u"HistogramChart",b"HistogramChart",u"LineChart",b"LineChart",u"Message",b"Message",u"Proposal",b"Proposal",u"Table",b"Table"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"BarChart",b"BarChart",u"HistogramChart",b"HistogramChart",u"LineChart",b"LineChart",u"Message",b"Message",u"Proposal",b"Proposal",u"Table",b"Table"]) -> None: ...
type___RuleResultBodyItem = RuleResultBodyItem

class RuleResultBody(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

    @property
    def Items(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[type___RuleResultBodyItem]: ...

    def __init__(self,
        *,
        Items : typing___Optional[typing___Iterable[type___RuleResultBodyItem]] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"Items",b"Items"]) -> None: ...
type___RuleResultBody = RuleResultBody

class RuleResult(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    Identifier: typing___Text = ...
    DisplayName: typing___Text = ...
    SectionIdentifier: typing___Text = ...

    @property
    def Body(self) -> type___RuleResultBody: ...

    def __init__(self,
        *,
        Identifier : typing___Optional[typing___Text] = None,
        DisplayName : typing___Optional[typing___Text] = None,
        Body : typing___Optional[type___RuleResultBody] = None,
        SectionIdentifier : typing___Optional[typing___Text] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"Body",b"Body",u"DisplayName",b"DisplayName",u"Identifier",b"Identifier",u"SectionIdentifier",b"SectionIdentifier"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"Body",b"Body",u"DisplayName",b"DisplayName",u"Identifier",b"Identifier",u"SectionIdentifier",b"SectionIdentifier"]) -> None: ...
type___RuleResult = RuleResult

class RuleResults(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

    @property
    def RuleResults(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[type___RuleResult]: ...

    def __init__(self,
        *,
        RuleResults : typing___Optional[typing___Iterable[type___RuleResult]] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"RuleResults",b"RuleResults"]) -> None: ...
type___RuleResults = RuleResults
